# Generated by Django 5.2.1 on 2025-05-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('nome', models.CharField(max_length=70)),
                ('cognome', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('ruolo', models.CharField(choices=[('cittadino', 'Cittadino'), ('urbanista', 'Urbanista'), ('tecnico', 'Tecnico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipalita',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('codice_postale', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cittadino',
            fields=[
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cittadino', serialize=False, to='SmartCity.utente')),
                ('data_nascita', models.DateField()),
                ('data_registrazione', models.DateField()),
                ('numero_cellulare', models.CharField(max_length=20, null=True)),
                ('notifiche_sms', models.BooleanField(default=False, null=True)),
                ('punteggio_attivita', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicoComunale',
            fields=[
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tecnicocomunale', serialize=False, to='SmartCity.utente')),
                ('specializzazione', models.CharField(max_length=155)),
                ('numero_matricola', models.CharField(max_length=16)),
                ('email_ufficio', models.EmailField(max_length=254)),
                ('telefono_ufficio', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urbanista',
            fields=[
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='urbanista', serialize=False, to='SmartCity.utente')),
                ('tipo', models.CharField(max_length=100)),
                ('qualifica', models.CharField(max_length=120)),
                ('bio', models.TextField()),
                ('valutazione_media', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='utente',
            name='codice_postale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='SmartCity.municipalita'),
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('ID_Progetto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('budget', models.FloatField()),
                ('stato', models.CharField(max_length=20)),
                ('approvato', models.BooleanField()),
                ('data_pubblicazione', models.DateField()),
                ('data_inizio', models.DateField(null=True)),
                ('data_fine', models.DateField(null=True)),
                ('codice_postale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='SmartCity.municipalita')),
                ('urbanista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='SmartCity.urbanista')),
            ],
        ),
        migrations.CreateModel(
            name='FaseProgetto',
            fields=[
                ('ID_FaseProgetto', models.AutoField(primary_key=True, serialize=False)),
                ('Titolo_FaseProgetto', models.CharField(max_length=40)),
                ('descrizione_fase', models.TextField()),
                ('data_inizioFase_stimata', models.DateField()),
                ('data_fineFase_stimata', models.DateField()),
                ('data_Inizio', models.DateField(null=True)),
                ('data_Fine', models.DateField(null=True)),
                ('completata', models.BooleanField()),
                ('note_tecniche', models.TextField(null=True)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi', to='SmartCity.progetto')),
            ],
        ),
        migrations.CreateModel(
            name='Votazione',
            fields=[
                ('ID_Votazione', models.AutoField(primary_key=True, serialize=False)),
                ('data_voto', models.DateField()),
                ('scelta', models.BooleanField()),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votazioni', to='SmartCity.progetto')),
                ('cittadino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votazioni', to='SmartCity.cittadino')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('ID_Recensione', models.AutoField(primary_key=True, serialize=False)),
                ('voto', models.IntegerField()),
                ('descrizione', models.TextField(null=True)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='SmartCity.progetto')),
                ('cittadino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='SmartCity.cittadino')),
            ],
        ),
        migrations.CreateModel(
            name='Gestisce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestioni', to='SmartCity.faseprogetto')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestioni', to='SmartCity.tecnicocomunale')),
            ],
            options={
                'unique_together': {('fase', 'tecnico')},
            },
        ),
    ]
