# Generated by Django 5.2.1 on 2025-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='\\progetti'),
        ),
    ]
