# Generated by Django 5.2.1 on 2025-05-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanista',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profilo_urbanista', serialize=False, to='SmartCity.utente'),
        ),
    ]
