# Generated by Django 5.2.1 on 2025-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0002_alter_urbanista_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittadino',
            name='data_registrazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
