# Generated by Django 5.2.1 on 2025-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0003_alter_progetto_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
