# Generated by Django 5.2.1 on 2025-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0003_alter_cittadino_data_registrazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cittadino',
            old_name='notifiche_sms',
            new_name='notifiche_email',
        ),
        migrations.RemoveField(
            model_name='cittadino',
            name='numero_cellulare',
        ),
        migrations.AddField(
            model_name='cittadino',
            name='occupazione',
            field=models.CharField(choices=[('studente', 'Studente'), ('impiegato', 'Impiegato'), ('libero_professionista', 'Libero Professionista'), ('disoccupato', 'Disoccupato'), ('pensionato', 'Pensionato'), ('casalinga', 'Casalinga/o'), ('altro', 'Altro')], default=('studente', 'Studente'), max_length=70),
        ),
        migrations.AlterField(
            model_name='urbanista',
            name='qualifica',
            field=models.CharField(choices=[('laurea_triennale_urbanistica', 'Laurea triennale in Urbanistica'), ('laurea_magistrale_pianificazione', 'Laurea magistrale in Pianificazione Territoriale'), ('master_urbanistica', 'Master in Urbanistica e Pianificazione Urbana'), ('dottorato_scienze_urbanistiche', 'Dottorato in Scienze Urbanistiche'), ('abilitazione_professionale', 'Abilitazione professionale all’esercizio della professione di Urbanista'), ('certificazione_gis', 'Certificazione in GIS (Geographic Information Systems)'), ('corso_rigenerazione', 'Corso di specializzazione in Rigenerazione Urbana'), ('esperto_sostenibilita', 'Esperto in Sostenibilità e Pianificazione Ambientale'), ('esperto_mobilita', 'Esperto in Mobilità Urbana e Trasporti'), ('certificazione_pmp', 'Certificazione in Project Management (es. PMP)'), ('esperto_politiche_abitative', 'Esperto in Politiche Abitative e Sociali'), ('esperto_normativa', 'Esperto in Normativa Urbanistica e Edilizia')], max_length=120),
        ),
        migrations.AlterField(
            model_name='urbanista',
            name='tipo',
            field=models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('esperto', 'Esperto')], max_length=100),
        ),
    ]
