# Generated by Django 5.2.1 on 2025-06-13 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0005_alter_progetto_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittadino',
            name='codice_postale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalita', to='SmartCity.municipalita'),
        ),
    ]
