# Generated by Django 5.2.1 on 2025-06-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0006_alter_cittadino_codice_postale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittadino',
            name='codice_postale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartCity.municipalita'),
        ),
    ]
