# Generated by Django 5.2.1 on 2025-06-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0008_alter_progetto_stato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progetto',
            name='approvato',
        ),
    ]
