# Generated by Django 5.2.1 on 2025-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0009_remove_progetto_approvato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittadino',
            name='occupazione',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='progetto',
            name='stato',
            field=models.CharField(choices=[('in_valutazione', 'In valutazione'), ('in_votazione', 'In votazione'), ('approvato', 'Approvato'), ('in_corso', 'In corso'), ('sospeso', 'Sospeso'), ('concluso', 'Concluso'), ('rifiutato', 'Rifiutato')], default='in_valutazione', max_length=20),
        ),
    ]
