# Generated by Django 5.2.1 on 2025-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0010_alter_cittadino_occupazione_alter_progetto_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittadino',
            name='occupazione',
            field=models.CharField(choices=[('studente', 'Studente'), ('impiegato', 'Impiegato'), ('libero_professionista', 'Libero Professionista'), ('disoccupato', 'Disoccupato'), ('pensionato', 'Pensionato'), ('casalinga', 'Casalinga/o'), ('altro', 'Altro')], default=('studente', 'Studente'), max_length=70),
        ),
    ]
