# Generated by Django 5.2.1 on 2025-06-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0013_alter_gestisce_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votazione',
            name='scelta',
        ),
    ]
