# Generated by Django 5.2.1 on 2025-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0014_remove_votazione_scelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='stato',
            field=models.CharField(choices=[('in_valutazione', 'In valutazione'), ('in_votazione', 'In votazione'), ('approvato', 'Approvato'), ('concluso', 'Concluso'), ('rifiutato', 'Rifiutato')], default='in_valutazione', max_length=20),
        ),
    ]
