# Generated by Django 5.2.1 on 2025-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0016_alter_progetto_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseprogetto',
            name='Titolo_FaseProgetto',
            field=models.CharField(choices=[('Progettazione_dettagliata', 'Progettazione dettagliata'), ('Approvazione_e_autorizzazioni', 'Approvazione e autorizzazioni'), ('Esecuzione_lavori', 'Esecuzione lavori'), ('Controllo_qualità_collaudo', 'Controllo qualità e collaudo'), ('Consegna_progetto', 'Consegna e chiusura progetto')], max_length=70),
        ),
        migrations.AlterField(
            model_name='faseprogetto',
            name='completata',
            field=models.BooleanField(default=False),
        ),
    ]
