# Generated by Django 5.2.1 on 2025-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0017_alter_faseprogetto_titolo_faseprogetto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='completato',
            field=models.BooleanField(default=False),
        ),
    ]
