# Generated by Django 5.2.1 on 2025-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0018_progetto_completato'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='data_fine_effettiva',
            field=models.DateField(default=None, null=True),
        ),
    ]
