# Generated by Django 5.2.1 on 2025-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0020_alter_progetto_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='stato',
            field=models.CharField(choices=[('in_valutazione', 'In valutazione'), ('in_votazione', 'In votazione'), ('concluso', 'Concluso'), ('in_corso', 'In Corso'), ('approvato', 'Approvato'), ('rifiutato', 'Rifiutato')], default='in_valutazione', max_length=20),
        ),
    ]
