# Generated by Django 5.2.1 on 2025-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0023_alter_urbanista_qualifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='stato_recensione',
            field=models.CharField(choices=[('recensito', 'Recensito'), ('non_recensito', 'Non Recensito')], default='non_recensito', max_length=20),
        ),
    ]
