# Generated by Django 5.2.1 on 2025-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0024_recensione_stato_recensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='totale_recensioni',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
