# Generated by Django 5.2.1 on 2025-06-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0025_recensione_totale_recensioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensione',
            name='totale_recensioni',
        ),
    ]
