# Generated by Django 5.2.1 on 2025-06-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0026_remove_recensione_totale_recensioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='tecnico_approvatore',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='SmartCity.tecnicocomunale'),
        ),
    ]
