# Generated by Django 5.2.1 on 2025-06-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity', '0029_alter_cittadino_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('ID_Badge', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.CharField(max_length=255)),
                ('soglia_punti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ottiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ottiene', to='SmartCity.badge')),
                ('cittadino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ottiene', to='SmartCity.cittadino')),
            ],
        ),
    ]
